<p>Welcome to the simple implementation of ZF2 base on ZF2 skeleton provided by Zend Framework 2</p>
<p> You can create a new MVC or Consume module using the bash tool provided here.</p>
<p> Here a few examples :</p>
<p> <strong>First</strong> You must locate the directory where bash.php script is. <span style="color: blue;">([APP_DIR]/data/scripts/bash/bash.php)</span></p>
<ul>
    <li><strong>#</strong> php bash.php -module:create user:mvc</li>
    <li><strong>#</strong> php bash.php -module:create library:consume</li>
</ul>